apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hios
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-hios@sha256:be3aeb20f1fe1e12b5653f0b4472993a60fed6cd5e5486d944f53a2203d3959a
        name: my-nodejs
        resources: {}
status: {}
